version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    tty: true
    volumes:
      - ./Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    ports:
      - 5432:5432          
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5 
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=betonflex
      - POSTGRES_SSL=false
      - SCHEMA=keycloack
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 3
  keycloack:
    image: quay.io/keycloak/keycloak:21.1
    command: ["start-dev", "--http-port=8888"]
    ports:
      - 8888:8888
    environment:
      - DB_SCHEMA=keycloack
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/betonflex
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./Docker-Compose/auth/realm.json:/opt/keycloak/data/import/realm.json