version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    tty: true
    volumes:
      - ./Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    ports:
      - 5432:5432          
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5 
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=betonflex
      - POSTGRES_SSL=false
  keycloack:
    image: quay.io/keycloak/keycloak:21.1
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./Docker-Compose/auth/realm.json:/opt/keycloak/data/import/realm.json      